### ISSUE TITLE
Как добавить на панель отображение текущей скорости вентилятора?

### ISSUE THREAD

**Issue by man55** [airens/tion_home_assistant#43]
Как добавить на панель отображение текущей скорости вентилятора?
Не нашел такого объекта(.
Спасибо.
![Screenshot 2023-02-08 132000](https://user-images.githubusercontent.com/30772900/217515973-2d7df88b-5cad-4a9b-acaf-0827799131cf.jpg)

**Comment by airens** [comment]
> Как добавить на панель отображение текущей скорости вентилятора? Не нашел такого объекта(. Спасибо. ![Screenshot 2023-02-08 132000](https://user-images.githubusercontent.com/30772900/217515973-2d7df88b-5cad-4a9b-acaf-0827799131cf.jpg)

Я делаю template sensor через атрибуты. Пример:
```yaml
      kitchen_breezer_output_temperature:
        friendly_name: "Kitchen breezer output temperature"
        value_template: "{{ state_attr('climate.kitchen_breezer', 'current_temperature') | int(0) }}"
        unit_of_measurement: "°C"
      kitchen_breezer_target_temperature:
        friendly_name: "Kitchen breezer target temperature"
        value_template: "{{ state_attr('climate.kitchen_breezer', 'temperature') | int(0) }}"
        unit_of_measurement: "°C"
      kitchen_breezer_speed:
        friendly_name: "Kitchen breezer speed"
        value_template: "{{ state_attr('climate.kitchen_breezer', 'speed') | int(0) }}"
        icon_template: "mdi:speedometer-medium"
        unit_of_measurement: 'spd'
      kitchen_breezer_speed_min:
        friendly_name: "Kitchen breezer speed min"
        value_template: "{{ state_attr('climate.kitchen_breezer', 'speed_min_set') | int(0) }}"
        icon_template: "mdi:speedometer-slow"
        unit_of_measurement: 'spd'
      kitchen_breezer_speed_max:
        friendly_name: "Kitchen breezer speed max"
        value_template: "{{ state_attr('climate.kitchen_breezer', 'speed_max_set') | int(0) }}"
        icon_template: "mdi:speedometer"
        unit_of_measurement: 'spd'
      kitchen_breezer_target_co2:
        friendly_name: "Kitchen breezer target co2"
        value_template: "{{ state_attr('climate.kitchen_breezer', 'target_co2') | int(0) }}"
        icon_template: "mdi:molecule-co2"
        unit_of_measurement: 'ppm'        
```
