### ISSUE TITLE
Не работает с  HA 2024.1

### ISSUE THREAD

**Issue by AlexeyTorch** [airens/tion_home_assistant#46]
Добрый день. 
Версия HA: 2024.1
Версия компонента 1.03
включено логгирование:
```
    custom_components.tion: info
    tion: info
```

При запуске выбора режима кодом
```
service: climate.set_fan_mode
target:
  entity_id:
    - climate.tion_bedroom
data:
  fan_mode: 0-3:600
```
при запуске в логе ошибка:

> 2024-01-05 09:20:48.962 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: sequence item 2: expected str instance, int found
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _async_step
>     await getattr(self, handler)()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 713, in _async_call_service_step
>     response_data = await self._async_run_long_action(
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 675, in _async_run_long_action
>     return long_task.result()
>            ^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2173, in async_call
>     response_data = await coro
>                     ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2210, in _execute_service
>     return await target(service_call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
>     return await service.entity_service_call(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
>     single_response = await _handle_entity_call(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
>     result = await task
>              ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 570, in async_handle_set_fan_mode_service
>     self._valid_mode_or_raise("fan", fan_mode, self.fan_modes)
>   File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 531, in _valid_mode_or_raise
>     modes_str: str = ", ".join(modes) if modes else ""
>                      ^^^^^^^^^^^^^^^^
> TypeError: sequence item 2: expected str instance, int found
> 2024-01-05 09:20:48.980 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140717754775872] Error handling message: Unknown error (unknown_error) Alex from 192.168.0.33 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0)
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
>     await func(hass, connection, msg)
>   File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 782, in handle_execute_script
>     script_result = await script_obj.async_run(
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1587, in async_run
>     return await asyncio.shield(run.async_run())
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 426, in async_run
>     await self._async_step(log_exceptions=False)
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 479, in _async_step
>     self._handle_exception(
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 502, in _handle_exception
>     raise exception
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _async_step
>     await getattr(self, handler)()
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 713, in _async_call_service_step
>     response_data = await self._async_run_long_action(
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 675, in _async_run_long_action
>     return long_task.result()
>            ^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2173, in async_call
>     response_data = await coro
>                     ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/core.py", line 2210, in _execute_service
>     return await target(service_call)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
>     return await service.entity_service_call(
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 882, in entity_service_call
>     single_response = await _handle_entity_call(
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 952, in _handle_entity_call
>     result = await task
>              ^^^^^^^^^^
>   File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 570, in async_handle_set_fan_mode_service
>     self._valid_mode_or_raise("fan", fan_mode, self.fan_modes)
>   File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 531, in _valid_mode_or_raise
>     modes_str: str = ", ".join(modes) if modes else ""
>                      ^^^^^^^^^^^^^^^^
> TypeError: sequence item 2: expected str instance, int found

При этом, выключение  командой
```
service: climate.set_hvac_mode
data:
  hvac_mode: "off"
target:
  entity_id:
    - climate.tion_bedroom
```
работает штатно

**Comment by shilin-da** [comment]
Тоже сломалось при вчерашнем обновлении. Ранее явного указания фиксированного режима в кавычках (например `'2'` вместо `2`) было достаточно. Но сейчас такой вариант не работает:
```
              - show_name: true
                show_icon: true
                type: button
                tap_action:
                  action: call-service
                  service: climate.set_fan_mode
                  target:
                    entity_id:
                      - climate.bedroom_breezer
                      - climate.nursery_breezer
                      - climate.lounge_breezer
                  data:
                    fan_mode: '2'
```
